--- 
title: "Analyse des données d'essai de nutrition de cailles"
author: "Tiho, T."
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
#bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
description: "The output format for this example is bookdown::gitbook."
---

# Travail demandé

## Analyse 1, Touré

Données Parkia - TOURÉ-2021

Variables explicatives :

- `org`, pour organe
- `ext`, pour extraction

Variables expliquées :

- `gae` pour mg GAE/g, => Gallic acid equivalent
- `qe` pour mg QE/g,   => Quercetin equivalent
- `te` pour μmol T.E/g => Trolox equivalent

Comparer les effets en tenant compte de l'interaction `org * ext`.



## Analyse 2, Tani


Feuillet NFS_Analysis (dnfs) - TANI-2021

Variables explicatives :

- `Aa`  : Acacia auriculiformis
- `Sex` : sexe

Variables expliquées :

- `wbc`	:  White blood cell (10^3/μL)
- `lym`	:  Lymphocytes (10^3/μL)
- `gran` : Granulocytes (10^3/μL)
- `rbc`	:  Red blood cell (10^6/μL)
- `hgb`	:  Hémoglobine (g/dL)
- `hct`	:  Hématocrite (%)
- `mcv`	:  Mean corpuscular volume (fL)
- `plt` :  Platelet (10^3/μL)
 
Comparer les effets en tenant compte de l'interaction `A.a * Sex`.



## Analyse 3, Gbané

Feuillet Egg_Analysis (degg) - GBANÉ-2021

Variables explicatives :

- `week` : semaine (NB, exclue)
- `diet` : régime

Variables expliquées :

- `Egg` : masse de l'oeuf (g) 	
- `Shel` : masse de la coquille (g) 	
- `Yol` : masse du jaune (g)
- `Alb` : masse du blanc (g)
- `indl`* : indice L
- `inda`* : indice a
- `indb`* : indice b
- `Tot_Chol` : Cholestérol total (mg/g)

Faire les ANOVA et graphiques nécessaires.

## Les librairies

```{r message = FALSE, warning = FALSE}
library(ggpubr)    # pour créer facilement des graphiques prêts à la publication
library(rstatix)   # contient des fonctions R facilitant les analyses statistiques
library(car)       # 
library(broom)     # 
library(GGally)    # ggpairs(), matrice de nuage de points
library(Rmisc)     # summarySE(), moy et IC essais factoriels, ...
library(multcomp)  # Tukey
library(agricolae) # SNK.test()
library(tidyverse) # dplyr, ggplot2
```

Il y a des conflits entre packages. Il faudra parfois rappeler le module avant la fonction. J'ai aussi chargé `tidyverse` en dernier en fonction.


